# Cloud Build configuration for deploying React app to Google App Engine
# Trigger this build by committing to your repository or manually via:
# gcloud builds submit --config cloudbuild.yaml .

steps:
  # Step 1: Install dependencies
  - id: "Install Dependencies"
    name: "node:20"
    entrypoint: "npm"
    args: ["install"]
    dir: "."

  # Step 2: Build the React application
  - id: "Build React App"
    name: "node:20"
    entrypoint: "npm"
    args: ["run", "build"]
    dir: "."
    env:
      - "NODE_ENV=production"

  # Step 3: Deploy to App Engine
  - id: "Deploy to App Engine"
    name: "gcr.io/cloud-builders/gcloud"
    args: 
      - "app"
      - "deploy"
      - "app.yaml"
      - "--quiet"
      - "--project=$PROJECT_ID"
    dir: "."

# Increase timeout for build and deployment
timeout: 1200s

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

